### PR TITLE
Added util methods for EventBroadcast

### PR DESCRIPTION
**Pull request by kliakos**

### CODE REVIEW

**Review by mariomac — APPROVED** [review]
Thank you for your contribution!

**Comment by kliakos** [comment]
These util methods can be used to skip event broadcasting if you have no subscribers.

Depending on the type of event you broadcast and the serialization required for the event data, this can save you some resources.

Also useful to monitor the number of subscribers.

**Comment by kliakos** [comment]
@mariomac can you publish new version to central maven repo, that will contain this update?

**Comment by mariomac** [comment]
Published as 0.11.0. Thank you for your contribution! Don't hesitate to ping me for any issue.

**Pull request merged**
